name: Test Artifact Upload

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dummy file
        run: |
          mkdir output
          echo Hello from radOS > output/hello.txt

      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-hello
          path: output/hello.txt
